const URL='https://zjetemcqysvpbnyvpyma.supabase.co',KEY='sb_publishable_jdeKO7PxDMGjAg_qCFw5FA_wr5OJcei';const db=supabase.createClient(URL,KEY);
let me,profile,data={customers:[],cases:[],payments:[],expenses:[],schedules:[],staff:[]};
const roles={owner:'負責人',manager:'主管',counselor:'禮儀師',accounting:'會計',staff:'一般員工'},statuses={pending:'待處理',signed:'已簽約',mourning:'治喪中',farewell:'告別式',cremation:'火化',interment:'晉塔',closed:'已結案',cancelled:'已取消'};
const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function money(x){return Number(x||0).toLocaleString('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0})}
function date(x){return x?new Date(x).toLocaleString('zh-TW'):'-'}
async function start(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});db.auth.onAuthStateChange(async(_,s)=>{if(s){await load(s.user);await refresh();show(true)}else show(false)});let{s}=await db.auth.getSession();if(s?.user){await load(s.user);await refresh();show(true)}}
async function load(u){me=u;let{data:d,error}=await db.from('staff_profiles').select('*').eq('user_id',u.id).single();if(error)throw error;if(!d.active)throw new Error('此員工帳號已停用');profile=d;$('role').textContent=roles[d.role]||d.role;$('user').textContent=`登入：${d.name}｜${d.email}`;$('staffNav').classList.toggle('hide',d.role!=='owner')}
function show(ok){$('login').classList.toggle('hide',ok);$('main').classList.toggle('hide',!ok)}
async function get(t,o='created_at'){let{data:d,error}=await db.from(t).select('*').order(o,{ascending:false});if(error)throw error;return d||[]}
async function refresh(){try{[data.customers,data.cases,data.payments,data.expenses,data.schedules]=await Promise.all([get('customers'),get('funeral_cases'),get('payments','payment_date'),get('expenses','expense_date'),get('schedules','start_at')]);render('home')}catch(e){alert(e.message)}}
function render(p){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));let h='';
if(p==='home'){let open=data.cases.filter(x=>!['closed','cancelled'].includes(x.status)).length;h=`<div class="head"><h2>首頁總覽</h2></div><div class="grid"><div class="stat">客戶<b>${data.customers.length}</b></div><div class="stat">進行中案件<b>${open}</b></div><div class="stat">收款筆數<b>${data.payments.length}</b></div><div class="stat">支出筆數<b>${data.expenses.length}</b></div></div><div class="card" style="margin-top:12px">系統已連接 Supabase 雲端資料庫。<br>本版本<strong>沒有身分證字號欄位</strong>。</div>`}
if(p==='customers'){h=`<div class="head"><h2>客戶管理</h2><button class="primary" onclick="addCustomer()">＋新增客戶</button></div><div class="table"><table><tr><th>姓名</th><th>電話</th><th>地址</th><th>關係</th><th>備註</th></tr>${data.customers.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.address)}</td><td>${esc(x.relation)}</td><td>${esc(x.notes)}</td></tr>`).join('')||'<tr><td colspan=5>目前沒有資料</td></tr>'}</table></div>`}
if(p==='cases'){h=`<div class="head"><h2>殯葬案件</h2><button class="primary" onclick="addCase()">＋新增案件</button></div><div class="table"><table><tr><th>案件編號</th><th>往生者</th><th>狀態</th><th>契約金額</th></tr>${data.cases.map(x=>`<tr><td>${esc(x.case_number)}</td><td>${esc(x.deceased_name)}</td><td>${statuses[x.status]||x.status}</td><td>${money(x.contract_amount)}</td></tr>`).join('')||'<tr><td colspan=4>目前沒有資料</td></tr>'}</table></div>`}
if(p==='finance'){let can=['owner','accounting'].includes(profile.role);h=`<div class="head"><h2>財務管理</h2>${can?'<span><button class="primary" onclick="addPayment()">＋收款</button> <button onclick="addExpense()">＋支出</button></span>':''}</div>${can?'':'<div class="notice">目前角色只能依 RLS 權限查看財務資料。</div>'}<div class="table"><table><tr><th>類別</th><th>說明</th><th>金額</th><th>狀態</th><th>日期</th></tr>${data.payments.map(x=>`<tr><td>收款</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${date(x.payment_date)}</td></tr>`).join('')}${data.expenses.map(x=>`<tr><td>支出</td><td>${esc(x.description)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${date(x.expense_date)}</td></tr>`).join('')||''}</table></div>`}
if(p==='schedules'){h=`<div class="head"><h2>行程管理</h2><button class="primary" onclick="addSchedule()">＋新增行程</button></div><div class="table"><table><tr><th>行程</th><th>時間</th><th>地點</th><th>備註</th></tr>${data.schedules.map(x=>`<tr><td>${esc(x.title)}</td><td>${date(x.start_at)}</td><td>${esc(x.location)}</td><td>${esc(x.notes)}</td></tr>`).join('')||'<tr><td colspan=4>目前沒有資料</td></tr>'}</table></div>`}
if(p==='staff'){h=`<div class="head"><h2>員工管理</h2></div><div class="notice">員工登入帳號先在 Supabase → Authentication → Users 建立；建立後再建立 staff_profiles。<br>目前不在前端建立密碼，也不儲存身分證字號。</div>`}
$('content').innerHTML=h}
async function addCustomer(){let n=prompt('客戶姓名');if(!n)return;let phone=prompt('電話')||'',address=prompt('地址')||'',relation=prompt('關係')||'',notes=prompt('備註')||'';let{error}=await db.from('customers').insert({name:n,phone,address,relation,notes,created_by:me.id});if(error)alert(error.message);else refresh()}
async function addCase(){let num=prompt('案件編號');if(!num)return;let name=prompt('往生者姓名');if(!name)return;let amount=Number(prompt('契約金額（可留空）')||0);let{error}=await db.from('funeral_cases').insert({case_number:num,deceased_name:name,contract_amount:amount,status:'pending',created_by:me.id});if(error)alert(error.message);else refresh()}
async function addPayment(){let c=data.cases[0];if(!c)return alert('請先建立案件');let a=Number(prompt('收款金額')||0);if(!a)return;let{error}=await db.from('payments').insert({case_id:c.id,amount:a,payment_date:new Date().toISOString().slice(0,10),description:prompt('說明')||'',status:'pending',created_by:me.id});if(error)alert(error.message);else refresh()}
async function addExpense(){let c=data.cases[0];if(!c)return alert('請先建立案件');let a=Number(prompt('支出金額')||0);if(!a)return;let{error}=await db.from('expenses').insert({case_id:c.id,amount:a,expense_date:new Date().toISOString().slice(0,10),description:prompt('說明')||'',status:'pending',created_by:me.id});if(error)alert(error.message);else refresh()}
async function addSchedule(){let title=prompt('行程名稱');if(!title)return;let loc=prompt('地點')||'',notes=prompt('備註')||'';let{error}=await db.from('schedules').insert({title,start_at:new Date().toISOString(),location:loc,notes,created_by:me.id});if(error)alert(error.message);else refresh()}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('msg').textContent='登入中…';let{error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('msg').textContent=error?error.message:''}
$('logout').onclick=()=>db.auth.signOut();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.page));window.addEventListener('load',start);
